import express from "express";
import path from "path";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
app.use(express.json());

const PORT = 3000;

// Lazy initialization of GoogleGenAI or secure fallback
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY o'rnatilmagan! Iltimos, Sozlamalar -> Secrets bo'limida API kalitini kiriting.");
    }
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        }
      }
    });
  }
  return aiClient;
}

// 1. Chat AI for Student Questions about Timetable
app.post("/api/gemini/chat", async (req, res) => {
  try {
    const { messages, scheduleContext, role, additionalContext } = req.body;
    
    if (!messages || !Array.isArray(messages)) {
      res.status(400).json({ error: "messages array kutilmoqda." });
      return;
    }

    const client = getGeminiClient();
    
    // Build a rich context for Gemini
    const systemPrompt = `Siz "Aqlli Dars Jadvali" universitet tizimining sun'iy intellekt yordamchisisiz.
Hozirgi foydalanuvchi roli: ${role || "student"}.
Universitet dars jadvali tizimi quyidagi ma'lumotlarga ega:
${JSON.stringify(scheduleContext || {})}

Qo'shimcha foydalanuvchi va tizim konteksti:
${JSON.stringify(additionalContext || {})}

Foydalanuvchiga faqat va faqat o'zbek tilida (yoki foydalanuvchi so'ragan tilda), juda samimiy, aniq va lutf bilan javob bering.
Dars jadvalining tafsilotlari, dushanbadan shanbagacha dars vaqtlari, o'qituvchilar kabinetlari yoki vazifalar so'ralganda shu ma'lumotlarga qat'iy asosan javob bering. Noaniq yoki yo'q ma'lumotni to'qib chiqarmang, topilmasa muloyimlik bilan ma'lumot yo'qligini bildiring. Foydalanuvchiga dars o'zgarishlari borasida tavsiyalar bering.`;

    // Convert messages format for Gemini generateContent
    // Since we're doing a single direct call with prompt context, we can send it as a conversation format
    const formattedContents = messages.map(msg => ({
      role: msg.sender === "user" ? "user" : "model",
      parts: [{ text: msg.content }]
    }));

    // Inject system instruction in config
    const response = await client.models.generateContent({
      model: "gemini-3.5-flash",
      contents: formattedContents,
      config: {
        systemInstruction: systemPrompt,
        temperature: 0.7,
      }
    });

    res.json({ text: response.text });
  } catch (error: any) {
    console.error("Gemini Chat Error:", error);
    res.status(500).json({ error: error.message || "Tizimda xatolik yuz berdi" });
  }
});

// 2. Schedule conflict resolution and smart auto-generation
app.post("/api/gemini/optimize", async (req, res) => {
  try {
    const { currentLessons, teachers, rooms, groups, requestedAction } = req.body;
    
    const client = getGeminiClient();

    const systemPrompt = `Siz dars jadvali shakllantiruvchi xodimning aqlli yordamchisisiz. Universitet dars jadvalidagi konfliktlarni (ustma-ust tushishlar) topish va jadvalni optimallashtirish bo'yicha mutaxassissiz.
Ma'lumotlar bazasi:
- Dars jadvali: ${JSON.stringify(currentLessons || [])}
- O'qituvchilar: ${JSON.stringify(teachers || [])}
- Xonalar: ${JSON.stringify(rooms || [])}
- Guruhlar: ${JSON.stringify(groups || [])}

Qilinishi kerak bo'lgan vazifa: ${requestedAction || "konfliktlarni tekshirish"}.

Siz JSON formatida javob qaytarishingiz kerak.
Javob formati quyidagicha bo'lishi shart (hech qanday markdown \`\`\`json belgisiz, faqat toza JSON obyekti bo'lsin):
{
  "conflicts": [
    {
      "type": "warning" yoki "error",
      "description": "Konflikt haqida o'zbekcha batafsil tushuntirish",
      "affectedLessons": ["s1", "s2"]
    }
  ],
  "suggestions": [
    {
      "title": "Optimallashtirish taklifi sarlavhasi",
      "description": "Nega bu taklif yaxshi ekanligi",
      "actionDetails": "Bajarilishi kerak bo'lgan dars o'zgartirishi: dars id-si, yangi kun, yangi para"
    }
  ],
  "autoGeneratedSlots": [
    {
      "groupId": "guruh_id",
      "groupName": "guruh_nomi",
      "subject": "fan_nomi",
      "teacherId": "o'qituvchi_id",
      "teacherName": "o'qituvchi_nomi",
      "room": "xona_nomi",
      "dayOfWeek": "Kun",
      "pairNumber": 1,
      "type": "Ma'ruza" yoki "Amaliyot"
    }
  ]
}

Konfliktlarni qidirishda qoidalarga e'tibor bering:
1. O'qituvchi ayni bir kun va ayni bir parrada ikkita alohida guruh bilan dars o'ta olmaydi.
2. Xona ayni bir kun va ayni bir parrada ikkita alohida dars uchun band bo'la olmaydi.
3. Guruh ayni bir kun va ayni bir parrada ikkita alohida darsga ega bo'la olmaydi.
4. Agar biron guruhning darslari uzilishlar bilan (masalan, 1-para bor, 2 yo'q, 3-para bor) joylashsa, buni 'warning' sifatida ko'rsating va optimallashtirish tavsiya qiling.`;

    const response = await client.models.generateContent({
      model: "gemini-3.5-flash",
      contents: "Iltimos, dars jadvalini optimallashtir va yuqoridagi qoidalarga ko'ra tahlil qil.",
      config: {
        systemInstruction: systemPrompt,
        responseMimeType: "application/json",
        temperature: 0.2,
      },
    });

    const textOutput = response.text || "{}";
    res.json(JSON.parse(textOutput.trim()));
  } catch (error: any) {
    console.error("Gemini Optimize Error:", error);
    res.status(500).json({ error: error.message || "Tizimda xatolik yuz berdi" });
  }
});

// Vite middleware for development or Static server for production
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const { createServer: createViteServer } = await import("vite");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
