import React, { useState } from "react";
import { 
  Calendar, 
  Sparkles, 
  Trash2, 
  Edit, 
  Plus, 
  RefreshCw, 
  Grid, 
  Check, 
  X, 
  AlertTriangle, 
  HelpCircle,
  Clock,
  BookOpen,
  MapPin,
  User,
  Users
} from "lucide-react";
import { DaySchedule, Teacher, Group, Room, LessonRequest, SystemLog } from "../types";
import { motion, AnimatePresence } from "motion/react";

interface StaffViewProps {
  schedule: DaySchedule[];
  setSchedule: React.Dispatch<React.SetStateAction<DaySchedule[]>>;
  teachers: Teacher[];
  groups: Group[];
  rooms: Room[];
  requests: LessonRequest[];
  setRequests: React.Dispatch<React.SetStateAction<LessonRequest[]>>;
  logs: SystemLog[];
  setLogs: React.Dispatch<React.SetStateAction<SystemLog[]>>;
}

const DAYS_OF_WEEK = ["Dushanba", "Seshanba", "Chorshanba", "Payshanba", "Juma", "Shanba"];

export default function StaffView({
  schedule,
  setSchedule,
  teachers,
  groups,
  rooms,
  requests,
  setRequests,
  logs,
  setLogs
}: StaffViewProps) {
  // Navigation tabs
  const [activeSubTab, setActiveSubTab] = useState<"builder" | "requests" | "ai-optimizer">("builder");

  // Editing / adding lesson state
  const [selectedDay, setSelectedDay] = useState<string>("Dushanba");
  const [editingLessonId, setEditingLessonId] = useState<string | null>(null);

  // Form states
  const [subject, setSubject] = useState("");
  const [teacherId, setTeacherId] = useState(teachers[0]?.id || "");
  const [groupId, setGroupId] = useState(groups[0]?.id || "");
  const [roomName, setRoomName] = useState(rooms[0]?.name || "");
  const [pairNumber, setPairNumber] = useState<number>(1);
  const [lessonType, setLessonType] = useState<DaySchedule["type"]>("Ma'ruza");

  // AI Optimizer States
  const [aiAnalyzing, setAiAnalyzing] = useState(false);
  const [aiResult, setAiResult] = useState<{
    conflicts: Array<{ type: "warning" | "error"; description: string; affectedLessons?: string[] }>;
    suggestions: Array<{ title: string; description: string; actionDetails: string }>;
    autoGeneratedSlots?: Array<any>;
  } | null>(null);
  const [aiError, setAiError] = useState("");

  // Resource Tahlil States
  const [tahlilDay, setTahlilDay] = useState<string>("Dushanba");
  const [tahlilPair, setTahlilPair] = useState<number>(1);

  const handleCreateOrUpdateLesson = (e: React.FormEvent) => {
    e.preventDefault();
    if (!subject) return;

    const teacherObj = teachers.find(t => t.id === teacherId);
    const groupObj = groups.find(g => g.id === groupId);

    const timePairs: Record<number, { start: string; end: string }> = {
      1: { start: "08:30", end: "09:50" },
      2: { start: "10:00", end: "11:20" },
      3: { start: "11:30", end: "12:50" },
      4: { start: "13:30", end: "14:50" },
      5: { start: "15:00", end: "16:20" },
    };

    if (editingLessonId) {
      // Update
      setSchedule(prev => prev.map(item => {
        if (item.id === editingLessonId) {
          return {
            ...item,
            subject,
            teacherId,
            teacherName: teacherObj ? teacherObj.name : "Noma'lum",
            groupId,
            groupName: groupObj ? groupObj.name : "Noma'lum",
            room: roomName,
            pairNumber,
            timeStart: timePairs[pairNumber].start,
            timeEnd: timePairs[pairNumber].end,
            type: lessonType,
            dayOfWeek: selectedDay,
          };
        }
        return item;
      }));
      
      // Log Action
      const newLog: SystemLog = {
        id: "log-" + Date.now(),
        user: "O'quv xodimi",
        action: `${selectedDay} kungi dars tahrirlandi: ${subject} (${groupObj?.name})`,
        time: new Date().toISOString().replace('T', ' ').substring(0, 16),
        role: "staff"
      };
      setLogs(prev => [newLog, ...prev]);

      setEditingLessonId(null);
    } else {
      // Create new
      const newLesson: DaySchedule = {
        id: "s-" + Date.now(),
        groupId,
        groupName: groupObj ? groupObj.name : "Noma'lum",
        subject,
        teacherId,
        teacherName: teacherObj ? teacherObj.name : "Noma'lum",
        room: roomName,
        dayOfWeek: selectedDay,
        pairNumber,
        timeStart: timePairs[pairNumber].start,
        timeEnd: timePairs[pairNumber].end,
        type: lessonType
      };

      setSchedule(prev => [...prev, newLesson]);

      // Log Action
      const newLog: SystemLog = {
        id: "log-" + Date.now(),
        user: "O'quv xodimi",
        action: `Yangi dars qo'shildi: ${subject} (${groupObj?.name}), ${selectedDay} ${pairNumber}-para`,
        time: new Date().toISOString().replace('T', ' ').substring(0, 16),
        role: "staff"
      };
      setLogs(prev => [newLog, ...prev]);
    }

    // Reset Form
    setSubject("");
  };

  const handleEditClick = (lesson: DaySchedule) => {
    setEditingLessonId(lesson.id);
    setSelectedDay(lesson.dayOfWeek);
    setSubject(lesson.subject);
    setGroupId(lesson.groupId);
    setTeacherId(lesson.teacherId);
    setRoomName(lesson.room);
    setPairNumber(lesson.pairNumber);
    setLessonType(lesson.type);
  };

  const handleDeleteLesson = (id: string, name: string) => {
    if (confirm(`Ushbu darsni jadvaldan butunlay o'chirishni xohlaysizmi: ${name}?`)) {
      setSchedule(prev => prev.filter(s => s.id !== id));
      
      const newLog: SystemLog = {
        id: "log-" + Date.now(),
        user: "O'quv xodimi",
        action: `Dars o'chirildi: ${name}`,
        time: new Date().toISOString().replace('T', ' ').substring(0, 16),
        role: "staff"
      };
      setLogs(prev => [newLog, ...prev]);
    }
  };

  // Resolve Teacher Request (Approve or Reject)
  const handleResolveRequest = (reqId: string, status: "approved" | "rejected") => {
    const request = requests.find(r => r.id === reqId);
    if (!request) return;

    if (status === "approved") {
      setSchedule(prev => prev.map(lesson => {
        if (lesson.id === request.lessonId) {
          if (request.type === "cancel") {
            // Cancel lesson - keep object but change subject to cancelled or remove?
            // Let's remove it
            return null;
          } else if (request.type === "room_change" && request.proposedRoom) {
            return { ...lesson, room: request.proposedRoom };
          } else if (request.type === "swap" && request.proposedPair) {
            const timePairs: Record<number, { start: string; end: string }> = {
              1: { start: "08:30", end: "09:50" },
              2: { start: "10:00", end: "11:20" },
              3: { start: "11:30", end: "12:50" },
              4: { start: "13:30", end: "14:50" },
              5: { start: "15:00", end: "16:20" },
            };
            return {
              ...lesson,
              pairNumber: request.proposedPair,
              timeStart: timePairs[request.proposedPair].start,
              timeEnd: timePairs[request.proposedPair].end,
            };
          }
        }
        return lesson;
      }).filter(Boolean) as DaySchedule[]);
    }

    // Change request status
    setRequests(prev => prev.map(r => r.id === reqId ? { ...r, status } : r));

    // Log action
    const newLog: SystemLog = {
      id: "log-" + Date.now(),
      user: "O'quv xodimi",
      action: `${request.teacherName} o'qituvchining so'rovi ${status === "approved" ? "TASDIQLANDI" : "RAD ETILDI"}`,
      time: new Date().toISOString().replace('T', ' ').substring(0, 16),
      role: "staff"
    };
    setLogs(prev => [newLog, ...prev]);
  };

  // Run AI Optimiser Integration
  const runAiOptimization = async (actionType: string, customActionText?: string) => {
    setAiAnalyzing(true);
    setAiError("");
    setAiResult(null);

    let finalAction = "";
    if (customActionText) {
      finalAction = customActionText;
    } else {
      finalAction = actionType === "conflicts" 
        ? "Dars jadvalidagi konfliktlar va xatolarni tekshir" 
        : "Guruhlar orasida bo'sh dars soatlarini (okno) optimallashtir va yangi darslar tavsiya qil";
    }

    try {
      const response = await fetch("/api/gemini/optimize", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          currentLessons: schedule,
          teachers,
          rooms,
          groups,
          requestedAction: finalAction
        })
      });

      const data = await response.json();
      if (response.ok) {
        setAiResult(data);
      } else {
        throw new Error(data.error || "Al optimallashtirish muvaffaqiyatsiz bo'ldi.");
      }
    } catch (err: any) {
      console.error(err);
      setAiError(`Xatolik: ${err.message}. Iltimos, server ishga tushganligini va API kalitingiz tekshirilganligini aniqlang.`);
    } finally {
      setAiAnalyzing(false);
    }
  };

  // Auto add AI recommended schedule slots
  const handleApplyAiGeneratedSlot = (slot: any) => {
    const timePairs: Record<number, { start: string; end: string }> = {
      1: { start: "08:30", end: "09:50" },
      2: { start: "10:00", end: "11:20" },
      3: { start: "11:30", end: "12:50" },
      4: { start: "13:30", end: "14:50" },
      5: { start: "15:00", end: "16:20" },
    };

    const newLesson: DaySchedule = {
      id: "s-" + Date.now(),
      groupId: slot.groupId,
      groupName: slot.groupName,
      subject: slot.subject,
      teacherId: slot.teacherId,
      teacherName: slot.teacherName,
      room: slot.room,
      dayOfWeek: slot.dayOfWeek,
      pairNumber: slot.pairNumber,
      timeStart: timePairs[slot.pairNumber]?.start || "08:30",
      timeEnd: timePairs[slot.pairNumber]?.end || "09:50",
      type: slot.type as any
    };

    setSchedule(prev => [...prev, newLesson]);
    
    // Clear recommendation from UI list to show progress
    if (aiResult?.autoGeneratedSlots) {
       setAiResult(prev => ({
         ...prev!,
         autoGeneratedSlots: prev!.autoGeneratedSlots?.filter(as => as.subject !== slot.subject || as.dayOfWeek !== slot.dayOfWeek)
       }));
    }

    // Log action
    const newLog: SystemLog = {
      id: "log-" + Date.now(),
      user: "O'quv xodimi",
      action: `AI tavsiyasi qo'llanildi: ${slot.subject} (${slot.groupName})`,
      time: new Date().toISOString().substring(0, 16),
      role: "staff"
    };
    setLogs(prev => [newLog, ...prev]);
  };

  return (
    <div className="space-y-6">
      {/* Subnavigation Headers */}
      <div className="flex border-b border-gray-100 pb-px gap-6">
        <button
          onClick={() => setActiveSubTab("builder")}
          className={`py-2 text-sm font-bold tracking-tight relative transition-all ${
            activeSubTab === "builder" ? "text-emerald-700" : "text-gray-400 hover:text-gray-900"
          }`}
        >
          Dars Jadvali Konstruktori
          {activeSubTab === "builder" && (
            <motion.div layoutId="subtab" className="absolute bottom-0 left-0 right-0 h-0.5 bg-emerald-600 rounded-full" />
          )}
        </button>

        <button
          onClick={() => setActiveSubTab("requests")}
          className={`py-2 text-sm font-bold tracking-tight relative transition-all flex items-center gap-1.5 ${
            activeSubTab === "requests" ? "text-emerald-700" : "text-gray-400 hover:text-gray-900"
          }`}
        >
          O'qituvchilar So'rovlari
          {requests.filter(r => r.status === "pending").length > 0 && (
            <span className="bg-red-500 text-white font-bold px-1.5 py-0.5 rounded-full text-[9px]">
              {requests.filter(r => r.status === "pending").length}
            </span>
          )}
          {activeSubTab === "requests" && (
            <motion.div layoutId="subtab" className="absolute bottom-0 left-0 right-0 h-0.5 bg-emerald-600 rounded-full" />
          )}
        </button>

        <button
          onClick={() => setActiveSubTab("ai-optimizer")}
          className={`py-2 text-sm font-bold tracking-tight relative transition-all flex items-center gap-1.5 ${
            activeSubTab === "ai-optimizer" ? "text-emerald-700" : "text-gray-400 hover:text-gray-900"
          }`}
        >
          <Sparkles className="w-3.5 h-3.5" />
          AI Super-Optimallashtiruvchi
          {activeSubTab === "ai-optimizer" && (
            <motion.div layoutId="subtab" className="absolute bottom-0 left-0 right-0 h-0.5 bg-emerald-600 rounded-full" />
          )}
        </button>
      </div>

      <AnimatePresence mode="wait">
        {activeSubTab === "builder" && (
          <motion.div
            key="builder"
            initial={{ opacity: 0, y: 5 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="grid grid-cols-1 xl:grid-cols-3 gap-6"
          >
            {/* Planner Form */}
            <div className="xl:col-span-1 bg-white rounded-3xl p-5 border border-gray-100 shadow-xs h-fit space-y-4">
              <div>
                <h3 className="font-bold text-gray-950 text-sm flex items-center gap-2">
                  <Grid className="w-4 h-4 text-emerald-600" />
                  {editingLessonId ? "Darsni Tahrirlash" : "Yangi Dars Qo'shish"}
                </h3>
                <p className="text-[10px] text-gray-400 mt-1">Guruhlar va o'qituvchilar dars paralarini yuklash</p>
              </div>

              <form onSubmit={handleCreateOrUpdateLesson} className="space-y-3.5 text-xs">
                <div>
                  <label className="block text-gray-700 font-medium mb-1">Fan / Kurs Nomi</label>
                  <input
                    type="text"
                    required
                    value={subject}
                    onChange={(e) => setSubject(e.target.value)}
                    placeholder="Masalan: Kiberxavfsizlik asoslari"
                    className="w-full p-2.5 rounded-xl border border-gray-200 focus:ring-1 focus:ring-emerald-500 text-xs focus:outline-none"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-gray-700 font-medium mb-1">Guruhni Tanlang</label>
                    <select
                      value={groupId}
                      onChange={(e) => setGroupId(e.target.value)}
                      className="w-full p-2.5 rounded-xl border border-gray-200 text-xs bg-white focus:outline-none focus:ring-1 focus:ring-emerald-500"
                    >
                      {groups.map(g => (
                        <option key={g.id} value={g.id}>{g.name}</option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="block text-gray-700 font-medium mb-1">O'qituvchi</label>
                    <select
                      value={teacherId}
                      onChange={(e) => setTeacherId(e.target.value)}
                      className="w-full p-2.5 rounded-xl border border-gray-200 text-xs bg-white focus:outline-none focus:ring-1 focus:ring-emerald-500"
                    >
                      {teachers.map(t => (
                        <option key={t.id} value={t.id}>{t.name}</option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-gray-700 font-medium mb-1">Auditoriya / Xona</label>
                    <select
                      value={roomName}
                      onChange={(e) => setRoomName(e.target.value)}
                      className="w-full p-2.5 rounded-xl border border-gray-200 text-xs bg-white focus:outline-none focus:ring-1 focus:ring-emerald-500"
                    >
                      {rooms.map(r => (
                        <option key={r.id} value={r.name}>{r.name}</option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="block text-gray-700 font-medium mb-1">Hafta Kuni</label>
                    <select
                      value={selectedDay}
                      onChange={(e) => setSelectedDay(e.target.value)}
                      className="w-full p-2.5 rounded-xl border border-gray-200 text-xs bg-white focus:outline-none focus:ring-1 focus:ring-emerald-500"
                    >
                      {DAYS_OF_WEEK.map(day => (
                        <option key={day} value={day}>{day}</option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-gray-700 font-medium mb-1">Dars Parasi</label>
                    <select
                      value={pairNumber}
                      onChange={(e) => setPairNumber(parseInt(e.target.value))}
                      className="w-full p-2.5 rounded-xl border border-gray-200 text-xs bg-white focus:outline-none focus:ring-1 focus:ring-emerald-500"
                    >
                      <option value={1}>1-para (08:30 - 09:50)</option>
                      <option value={2}>2-para (10:00 - 11:20)</option>
                      <option value={3}>3-para (11:30 - 12:50)</option>
                      <option value={4}>4-para (13:30 - 14:50)</option>
                      <option value={5}>5-para (15:00 - 16:20)</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-gray-700 font-medium mb-1">Mashg'ulot Turi</label>
                    <select
                      value={lessonType}
                      onChange={(e) => setLessonType(e.target.value as any)}
                      className="w-full p-2.5 rounded-xl border border-gray-200 text-xs bg-white focus:outline-none focus:ring-1 focus:ring-emerald-500"
                    >
                      <option value="Ma'ruza">Ma'ruza</option>
                      <option value="Amaliyot">Amaliyot</option>
                      <option value="Laboratoriya">Laboratoriya</option>
                      <option value="Seminar">Seminar</option>
                    </select>
                  </div>
                </div>

                <div className="flex gap-2 pt-2">
                  <button
                    type="submit"
                    className="flex-1 py-2.5 bg-emerald-600 hover:bg-emerald-555 transition-colors text-white font-bold rounded-xl text-xs flex items-center justify-center gap-1.5 cursor-pointer"
                  >
                    {editingLessonId ? "O'zgarishlarni Saqlash" : "Jadvalga Kiritish"}
                  </button>

                  {editingLessonId && (
                    <button
                      type="button"
                      onClick={() => {
                        setEditingLessonId(null);
                        setSubject("");
                      }}
                      className="px-3.5 py-2.5 bg-gray-100 hover:bg-gray-200 transition-colors text-gray-600 font-bold rounded-xl text-xs flex items-center justify-center cursor-pointer"
                    >
                      Bekor qilish
                    </button>
                  )}
                </div>
              </form>
            </div>

            {/* Timetable Grid View */}
            <div className="xl:col-span-2 space-y-4">
              <div className="bg-white rounded-3xl p-5 border border-gray-100 shadow-xs">
                <div className="flex justify-between items-center mb-4">
                  <div>
                    <h3 className="font-bold text-gray-900 tracking-tight text-sm">Haftalik barcha darslar tizmasi</h3>
                    <p className="text-[10px] text-gray-400">Har bir kun jadvalini tanlab nazorat qiling</p>
                  </div>

                  {/* Day picker buttons */}
                  <div className="flex gap-1 overflow-x-auto scrollbar-hide py-1">
                    {DAYS_OF_WEEK.map(d => (
                      <button
                        key={d}
                        onClick={() => setSelectedDay(d)}
                        className={`px-3 py-1.5 rounded-xl text-[10px] font-bold transition-all ${
                          selectedDay === d ? "bg-slate-900 text-white" : "bg-gray-50 text-gray-500 hover:bg-gray-100"
                        }`}
                      >
                        {d}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="space-y-3">
                  {schedule.filter(s => s.dayOfWeek === selectedDay).length === 0 ? (
                    <div className="text-center py-10 text-xs text-gray-450 border border-dashed border-gray-150 rounded-2xl bg-gray-50/50">
                      Ushbu {selectedDay} kuni uchun hali dars rejalashtirilmagan
                    </div>
                  ) : (
                    schedule
                      .filter(s => s.dayOfWeek === selectedDay)
                      .sort((a,b) => a.pairNumber - b.pairNumber)
                      .map((lesson) => (
                        <div key={lesson.id} className="p-3.5 bg-slate-50 border border-gray-150 hover:bg-slate-100/50 hover:border-emerald-150 rounded-2xl flex flex-col md:flex-row justify-between items-start md:items-center gap-4 transition-all duration-200">
                          <div className="flex items-start gap-3">
                            <span className="w-8 h-8 rounded-lg bg-emerald-50 text-emerald-800 border border-emerald-120 font-bold flex items-center justify-center text-xs">
                              {lesson.pairNumber}
                            </span>
                            <div>
                              <p className="font-bold text-gray-900 text-sm leading-tight">{lesson.subject}</p>
                              <p className="text-[10px] text-gray-500 mt-1">
                                Guruh: <span className="font-semibold">{lesson.groupName}</span> • O'qituvchi: <span className="font-serif">{lesson.teacherName}</span> • Turi: {lesson.type}
                              </p>
                              <p className="text-[10px] text-emerald-800 font-mono mt-0.5 flex items-center gap-1">
                                <MapPin className="w-3 h-3" />
                                {lesson.room} ({lesson.timeStart} - {lesson.timeEnd})
                              </p>
                            </div>
                          </div>

                          <div className="flex gap-1.5 self-end md:self-center">
                            <button
                              onClick={() => handleEditClick(lesson)}
                              className="p-1.5 bg-white hover:bg-blue-50 text-blue-650 rounded-lg border border-gray-150 hover:border-blue-200 transition-colors cursor-pointer"
                              title="Tahrirlash"
                            >
                              <Edit className="w-3.5 h-3.5" />
                            </button>
                            <button
                              onClick={() => handleDeleteLesson(lesson.id, lesson.subject)}
                              className="p-1.5 bg-white hover:bg-red-50 text-red-600 rounded-lg border border-gray-150 hover:border-red-200 transition-colors cursor-pointer"
                              title="O'chirish"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        </div>
                      ))
                  )}
                </div>
              </div>
            </div>
          </motion.div>
        )}

        {activeSubTab === "requests" && (
          <motion.div
            key="requests"
            initial={{ opacity: 0, y: 5 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="bg-white rounded-3xl p-6 border border-gray-100 shadow-xs space-y-4"
          >
            <div>
              <h3 className="font-bold text-gray-950 text-sm">O'qituvchilardan kelgan o'zgartirish so'rovlari yuklamasi</h3>
              <p className="text-[11px] text-gray-400 mt-1">Pedagogik sabablarga ko'ra darslarni optimallashtirish arizalari</p>
            </div>

            {requests.length === 0 ? (
              <div className="text-center py-10 text-xs text-gray-400">Hech qanday so'rovlar mavjud emas</div>
            ) : (
              <div className="space-y-3.5">
                {requests.map((req) => {
                  const lesson = schedule.find(s => s.id === req.lessonId);
                  return (
                    <div key={req.id} className="p-4 bg-gray-50 rounded-2xl border border-gray-100 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                      <div className="space-y-1.5 text-xs">
                        <div className="flex items-center gap-2">
                          <span className={`px-2 py-0.5 rounded-md text-[9px] font-bold uppercase ${
                            req.type === "room_change" ? "bg-blue-50 text-blue-700" : req.type === "cancel" ? "bg-red-50 text-red-700" : "bg-purple-50 text-purple-700"
                          }`}>
                            {req.type === "room_change" ? "Auditoriyani almashtirish" : req.type === "cancel" ? "Dars mashg'ulotini bekor qilish" : "Dars vaqtini o'zgartirish"}
                          </span>
                          <span className="font-semibold text-gray-901">Murojaatchi: {req.teacherName}</span>
                        </div>

                        <p className="font-bold text-sm text-gray-900 mt-1">
                          Asosiy dars: {lesson ? `${lesson.subject} (${lesson.groupName}) - ${lesson.dayOfWeek} ${lesson.pairNumber}-para` : "Noma'lum dars"}
                        </p>

                        <p className="text-gray-500 leading-snug">
                          <strong>Asos:</strong> "{req.reason}"
                        </p>

                        {req.proposedRoom && (
                          <p className="text-emerald-800 font-semibold bg-emerald-50 px-2 py-0.5 rounded-lg w-fit">
                            Taklif qilingan yangi xona: {req.proposedRoom}
                          </p>
                        )}

                        {req.proposedPair && (
                          <p className="text-emerald-800 font-semibold bg-emerald-50 px-2 py-0.5 rounded-lg w-fit">
                            Taklif qilingan yangi dars parasi: {req.proposedPair}-para
                          </p>
                        )}
                      </div>

                      <div className="shrink-0 flex items-center gap-2 self-end md:self-center">
                        {req.status === "pending" ? (
                          <>
                            <button
                              onClick={() => handleResolveRequest(req.id, "approved")}
                              className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl font-bold flex items-center gap-1 transition-colors cursor-pointer text-xs"
                            >
                              <Check className="w-3.5 h-3.5" />
                              Tasdiqlash
                            </button>
                            <button
                              onClick={() => handleResolveRequest(req.id, "rejected")}
                              className="px-3 py-1.5 bg-red-50 hover:bg-red-100 text-red-700 rounded-xl font-bold flex items-center gap-1 transition-colors cursor-pointer text-xs"
                            >
                              <X className="w-3.5 h-3.5" />
                              Rad etish
                            </button>
                          </>
                        ) : (
                          <span className={`px-3 py-1 rounded-full font-bold text-xs ${
                            req.status === "approved" ? "bg-emerald-50 text-emerald-800" : "bg-red-50 text-red-750"
                          }`}>
                            {req.status === "approved" ? "Tasdiqlangan" : "Rad etilgan"}
                          </span>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </motion.div>
        )}

        {activeSubTab === "ai-optimizer" && (
          <motion.div
            key="ai-optimizer"
            initial={{ opacity: 0, y: 5 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="bg-white rounded-3xl p-6 border border-gray-100 shadow-xs space-y-6"
          >
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 pb-4 border-b border-gray-100">
              <div>
                <h3 className="font-bold text-gray-950 text-base flex items-center gap-1.5">
                  <Sparkles className="w-5 h-5 text-emerald-600 animate-pulse" />
                  Sun'iy Intellekt dars jadvalini optimallashtirish bozori
                </h3>
                <p className="text-xs text-gray-400 mt-1">Ushbu tizim o'qituvchilar dars paralarining ustma-ust tushishi, xonalar bandligi va guruhlar o'rtasidagi dars uzilishlariga barham beradi.</p>
              </div>

              <div className="flex gap-2">
                <button
                  type="button"
                  disabled={aiAnalyzing}
                  onClick={() => runAiOptimization("conflicts")}
                  className="px-4 py-2 bg-slate-900 text-white font-bold rounded-xl text-xs flex items-center gap-1.5 hover:bg-slate-800 disabled:opacity-50 cursor-pointer transition-all"
                >
                  <AlertTriangle className="w-4 h-4 text-emerald-400" />
                  Konfliktlarni qidirish
                </button>

                <button
                  type="button"
                  disabled={aiAnalyzing}
                  onClick={() => runAiOptimization("builder")}
                  className="px-4 py-2 bg-emerald-600 text-white font-bold rounded-xl text-xs flex items-center gap-1.5 hover:bg-emerald-500 disabled:opacity-50 cursor-pointer transition-all"
                >
                  <Sparkles className="w-4 h-4 text-yellow-300" />
                  Bo'sh dars soatlarini qoplash
                </button>
              </div>
            </div>

            {/* Real-time Room & Teacher Availability Analyzer */}
            <div className="bg-slate-50 rounded-2xl p-5 border border-gray-200">
              <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4 mb-4 pb-4 border-b border-gray-200">
                <div>
                  <h4 className="font-extrabold text-sm text-gray-901 flex items-center gap-1.5">
                    <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse"></span>
                    AI Bandlik & Bo'sh Auditoriyalar Real-Vaqt Tahlili
                  </h4>
                  <p className="text-[11px] text-gray-500 mt-0.5">Haftalik kunlar va paralar kesimida bo'sh xonalar hamda o'qituvchilar bandligini avtomatik tahlil qiling.</p>
                </div>

                <div className="flex gap-2.5 flex-wrap">
                  {/* Select Day */}
                  <select
                    value={tahlilDay}
                    onChange={(e) => setTahlilDay(e.target.value)}
                    className="p-2 border border-gray-300 rounded-xl bg-white text-xs font-semibold focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  >
                    {DAYS_OF_WEEK.map(day => (
                      <option key={day} value={day}>{day}</option>
                    ))}
                  </select>

                  {/* Select Pair */}
                  <select
                    value={tahlilPair}
                    onChange={(e) => setTahlilPair(Number(e.target.value))}
                    className="p-2 border border-gray-300 rounded-xl bg-white text-xs font-semibold focus:outline-none focus:ring-1 focus:ring-emerald-500"
                  >
                    {[1, 2, 3, 4, 5].map(pair => (
                      <option key={pair} value={pair}>{pair}-para</option>
                    ))}
                  </select>
                </div>
              </div>

              {/* Dynamic calculations */}
              {(() => {
                // Find all active lessons for that day & pair
                const currentActiveLessons = schedule.filter(
                  (s) => s.dayOfWeek === tahlilDay && s.pairNumber === tahlilPair
                );

                // Busy rooms
                const busyRoomNames = currentActiveLessons.map((l) => l.room);
                const emptyClassrooms = rooms.filter((r) => !busyRoomNames.includes(r.name));

                // Busy teachers
                const busyTeacherIds = currentActiveLessons.map((l) => l.teacherId);
                const vacantTeachers = teachers.filter((t) => !busyTeacherIds.includes(t.id));
                const busyTeachersList = teachers.filter((t) => busyTeacherIds.includes(t.id));

                // Busy groups
                const busyGroupIds = currentActiveLessons.map((l) => l.groupId);
                const unoccupiedGroups = groups.filter((g) => !busyGroupIds.includes(g.id));

                // Build custom summary prompt for this exact hour
                const suggestionPrompt = `Dars jadvali tahlili va optimallashtirish bo'yicha maxsus vazifa:
Hafta kuni: ${tahlilDay}, Para: ${tahlilPair}-para.
Sizga berilgan resurs holati:
- Bo'sh auditoriyalar (xonalar): [${emptyClassrooms.map(r => `${r.name} (${r.type}, sig'imi: ${r.capacity} kishi)`).join(", ")}]
- Mashg'uloti yo'q (bo'sh) o'qituvchilar: [${vacantTeachers.map(t => `${t.name} (bo'limi: ${t.department})`).join(", ")}]
- Dars jadvalida bo'sh turgan guruhlar (ehtimoliy okno/bo'sh vaqtga ega): [${unoccupiedGroups.map(g => `${g.name} (${g.studentCount} kishi)`).join(", ")}]

Iltimos, ushbu bo'sh resurslar va guruhlarni inobatga olgan holda qo'shimcha darslarni dars jadvaliga kiritish uchun "autoGeneratedSlots" ro'yxatida aniq dars takliflarini shakllantiring.`;

                return (
                  <div className="space-y-4">
                    {/* Visual stats panel */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                      {/* Empty Classrooms stats */}
                      <div className="bg-white p-4.5 rounded-2xl border border-gray-150 shadow-3xs">
                        <div className="flex justify-between items-center mb-2.5">
                          <span className="text-xs font-extrabold text-emerald-800 bg-emerald-50 px-2.5 py-1 rounded-lg border border-emerald-100 flex items-center gap-1">
                            <MapPin className="w-3.5 h-3.5" /> Bo'sh Xonalar
                          </span>
                          <span className="font-mono text-sm font-bold text-gray-900">{emptyClassrooms.length} ta xona</span>
                        </div>
                        
                        <div className="space-y-1.5 max-h-[140px] overflow-y-auto pr-1">
                          {emptyClassrooms.length === 0 ? (
                            <p className="text-[11px] text-gray-400 italic">Hamma xonalar band</p>
                          ) : (
                            emptyClassrooms.map((room) => (
                              <div key={room.id} className="p-1.5 hover:bg-emerald-50/20 rounded-lg flex justify-between items-center text-[11px] border border-gray-100 bg-emerald-50/5">
                                <span className="font-bold text-gray-800">{room.name}</span>
                                <span className="text-gray-500">{room.type} ({room.capacity} o'rin)</span>
                              </div>
                            ))
                          )}
                        </div>
                      </div>

                      {/* Free teachers statistics */}
                      <div className="bg-white p-4.5 rounded-2xl border border-gray-150 shadow-3xs">
                        <div className="flex justify-between items-center mb-2.5">
                          <span className="text-xs font-extrabold text-blue-800 bg-blue-50 px-2.5 py-1 rounded-lg border border-blue-100 flex items-center gap-1">
                            <User className="w-3.5 h-3.5" /> Bo'sh O'qituvchilar
                          </span>
                          <span className="font-mono text-sm font-bold text-gray-900">{vacantTeachers.length} nafar</span>
                        </div>
                        
                        <div className="space-y-1.5 max-h-[140px] overflow-y-auto pr-1">
                          {vacantTeachers.length === 0 ? (
                            <p className="text-[11px] text-gray-400 italic">Barcha ustozlar darsda</p>
                          ) : (
                            vacantTeachers.map((teach) => (
                              <div key={teach.id} className="p-1.5 hover:bg-blue-50/20 rounded-lg flex justify-between items-center text-[11px] border border-gray-100 bg-blue-50/5">
                                <span className="font-bold text-gray-850">{teach.name}</span>
                                <span className="text-gray-400 truncate max-w-[120px]" title={teach.department}>{teach.department}</span>
                              </div>
                            ))
                          )}
                        </div>
                      </div>

                      {/* Busy/Teaching Teachers */}
                      <div className="bg-white p-4.5 rounded-2xl border border-gray-150 shadow-3xs">
                        <div className="flex justify-between items-center mb-2.5">
                          <span className="text-xs font-extrabold text-amber-800 bg-amber-50 px-2.5 py-1 rounded-lg border border-amber-100 flex items-center gap-1">
                            <Users className="w-3.5 h-3.5" /> Band O'qituvchilar (Darsda)
                          </span>
                          <span className="font-mono text-sm font-bold text-gray-900">{busyTeachersList.length} nafar</span>
                        </div>
                        
                        <div className="space-y-1.5 max-h-[140px] overflow-y-auto pr-1">
                          {busyTeachersList.length === 0 ? (
                            <p className="text-[11px] text-gray-400 italic">Hech kim dars o'tmayapti</p>
                          ) : (
                            busyTeachersList.map((teach) => {
                              const matchingLesson = currentActiveLessons.find((cl) => cl.teacherId === teach.id);
                              return (
                                <div key={teach.id} className="p-1.5 hover:bg-amber-50/20 rounded-lg flex flex-col gap-0.5 text-[11px] border border-gray-100 bg-amber-50/5">
                                  <div className="flex justify-between font-bold text-gray-850">
                                    <span>{teach.name}</span>
                                    <span className="text-[9px] bg-amber-100 text-amber-900 px-1.5 py-0.5 rounded-md">Darsda</span>
                                  </div>
                                  <p className="text-[9px] text-gray-500 truncate">Kurs: {matchingLesson?.subject} ({matchingLesson?.groupName} / {matchingLesson?.room})</p>
                                </div>
                              );
                            })
                          )}
                        </div>
                      </div>
                    </div>

                    {/* AI trigger block customized for these parameters */}
                    <div className="p-4 bg-emerald-600 rounded-2xl shadow-3xs border border-emerald-500 text-white flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                      <div className="space-y-1">
                        <h5 className="font-bold text-xs flex items-center gap-1.5">
                          <Sparkles className="w-3.5 h-3.5 text-yellow-300 animate-pulse" />
                          AI-bilan Resurslarni Optimal Rejalashtirish
                        </h5>
                        <p className="text-[10px] text-emerald-100 max-w-2xl leading-relaxed">
                          Gemini 3.5 ushbu tanlangan vaqtdagi ({tahlilDay}, {tahlilPair}-para) bo'sh turgan <strong>{emptyClassrooms.length} ta xonani</strong>, 
                          <strong> {vacantTeachers.length} nafar o'qituvchini</strong> va darslari kam guruhlarni hisobga olib optimal dars joylashtirishni taklif qiladi.
                        </p>
                      </div>

                      <button
                        type="button"
                        disabled={aiAnalyzing}
                        onClick={() => runAiOptimization("resource-placement", suggestionPrompt)}
                        className="px-4 py-2 bg-slate-900 hover:bg-slate-950 transition-all text-white font-bold rounded-xl text-xs flex items-center gap-1.5 shrink-0 self-end sm:self-center cursor-pointer shadow-sm active:scale-95 disabled:opacity-50"
                      >
                        <Sparkles className="w-3.5 h-3.5 text-yellow-300" />
                        Optimal joylashtirishni taklif etish
                      </button>
                    </div>
                  </div>
                );
              })()}
            </div>

            {aiAnalyzing && (
              <div className="text-center py-16 space-y-3">
                <RefreshCw className="w-9 h-9 text-emerald-600 animate-spin mx-auto" />
                <p className="text-sm font-semibold text-gray-800 animate-pulse">Gemini 3.5 AI jadvalni to'liq tahlil qilmoqda...</p>
                <p className="text-xs text-gray-400 max-w-md mx-auto">Xonalarning sig'imi, o'qituvchining dars soatlari va guruhlarning dars jadvallari matrisi birma-bir tahlildan o'tkazilyapti.</p>
              </div>
            )}

            {aiError && (
              <div className="p-4 bg-red-50 text-red-700 border-2 border-red-150 rounded-2xl text-xs font-semibold">
                {aiError}
              </div>
            )}

            {!aiAnalyzing && !aiResult && !aiError && (
              <div className="text-center py-12 bg-gray-50 rounded-2xl border border-dashed border-gray-200">
                <Sparkles className="w-12 h-12 text-gray-200 mx-auto mb-3" />
                <h4 className="font-semibold text-gray-800 text-sm">Sun'iy intellekt tahlilini boshlang</h4>
                <p className="text-xs text-gray-400 max-w-sm mx-auto mt-1">Yuqoridagi tugmalardan birini bosish orqali darslar orasidagi cheklov buzilishlarini yoki optimallashtirish rejalarini oling.</p>
              </div>
            )}

            {aiResult && (
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {/* Left Side: Conflicts and Warnings */}
                <div className="space-y-4">
                  <h4 className="font-bold text-sm text-gray-905 border-b border-gray-100 pb-2">Konfliktlar & Xatoliklar ({aiResult.conflicts?.length || 0})</h4>
                  
                  {(!aiResult.conflicts || aiResult.conflicts.length === 0) ? (
                    <div className="p-4 bg-emerald-50 text-emerald-800 border border-emerald-100 rounded-2xl text-xs font-semibold flex items-center gap-2">
                      <Check className="w-4 h-4" /> Dars jadvalida o'qituvchilar va xonalar orasida hech qanday konflikt topilmadi!
                    </div>
                  ) : (
                    <div className="space-y-2.5">
                      {aiResult.conflicts.map((c, i) => (
                        <div key={i} className={`p-3.5 rounded-2xl border flex items-start gap-2.5 text-xs font-semibold ${
                          c.type === "error" ? "bg-red-50 text-red-800 border-red-100" : "bg-amber-50 text-amber-800 border-amber-100"
                        }`}>
                          <AlertTriangle className={`w-4 h-4 shrink-0 mt-0.5 ${c.type === "error" ? "text-red-600" : "text-amber-600"}`} />
                          <div>
                            <p>{c.description}</p>
                            {c.affectedLessons && c.affectedLessons.length > 0 && (
                              <p className="text-[10px] text-gray-500 font-mono mt-1">Dars ID-lari: {c.affectedLessons.join(", ")}</p>
                            )}
                          </div>
                        </div>
                      ))}
                    </div>
                  )}

                  {/* Suggestions List */}
                  <h4 className="font-bold text-sm text-gray-905 border-b border-gray-100 pb-2 pt-4">Tizimni yaxshilash/tavsiya etish takliflari</h4>
                  
                  {(!aiResult.suggestions || aiResult.suggestions.length === 0) ? (
                    <div className="text-xs text-gray-400 py-4">Tizimni yanada takomillashtirish bo'yicha qo'shimcha taklif kiritilmadi.</div>
                  ) : (
                    <div className="space-y-2.5">
                      {aiResult.suggestions.map((s, i) => (
                        <div key={i} className="p-3.5 bg-gray-50 rounded-2xl border border-gray-100 text-xs">
                          <p className="font-bold text-gray-900">{s.title}</p>
                          <p className="text-gray-500 mt-1">{s.description}</p>
                          <p className="text-[10px] text-emerald-800 font-semibold bg-emerald-50 px-2 py-0.5 rounded-lg w-fit mt-2">{s.actionDetails}</p>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {/* Right Side: Generated recommended slots (Auto Scheduler) */}
                <div className="space-y-4">
                  <h4 className="font-bold text-sm text-gray-905 border-b border-gray-100 pb-2">AI tomonidan avtomatik to'ldirilgan dillar ({aiResult.autoGeneratedSlots?.length || 0})</h4>

                  {(!aiResult.autoGeneratedSlots || aiResult.autoGeneratedSlots.length === 0) ? (
                    <div className="text-xs text-gray-400 py-10 text-center bg-gray-50 rounded-2xl border border-dashed border-gray-150">
                      Taklif bo'sh dars soatlarini qoplash bo'yicha hech qanday yangi slot aniqlanmadi.
                    </div>
                  ) : (
                    <div className="space-y-3">
                      {aiResult.autoGeneratedSlots.map((slot, i) => (
                        <div key={i} className="p-4 bg-white hover:bg-emerald-50/20 rounded-2xl border border-dashed border-emerald-250 flex justify-between items-center gap-4 transition-all hover:border-emerald-400">
                          <div className="text-xs">
                            <p className="font-bold text-gray-900 text-sm leading-tight">{slot.subject}</p>
                            <p className="text-gray-500 mt-1 font-semibold">Guruh: {slot.groupName} • {slot.teacherName}</p>
                            <div className="flex gap-2 items-center flex-wrap text-[10px] text-emerald-800 font-mono mt-1.5">
                              <span className="bg-emerald-50 px-2 py-0.5 rounded-lg border border-emerald-100">{slot.dayOfWeek}</span>
                              <span className="bg-emerald-50 px-2 py-0.5 rounded-lg border border-emerald-100">{slot.pairNumber}-para</span>
                              <span className="bg-emerald-50 px-2 py-0.5 rounded-lg border border-emerald-100">{slot.room}</span>
                            </div>
                          </div>

                          <button
                            onClick={() => handleApplyAiGeneratedSlot(slot)}
                            className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl font-bold font-sans text-[11px] shrink-0 cursor-pointer flex items-center gap-1 transition-transform active:scale-95"
                          >
                            <Plus className="w-3 text-white h-3" />
                            Kiritish
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
